import _ from "lodash"

export const CHATMESSAGE_TYPE_URL = "URL"
export const CHATMESSAGE_TYPE_FILE = "FILE"
export const CHATMESSAGE_TYPE_TEXT = "TEXT"
export const CHATMESSAGE_TYPE_IMAGE = "IMAGE"
export const CHATMESSAGE_TYPE_STICKER = "STICKER"
export const CHATMESSAGE_TYPE_VIDEO = "VIDEO"
export const CHATMESSAGE_TYPE_RECORDING = "RECORDING"

export const CHATMESSAGE_TYPE = {
  CHATMESSAGE_TYPE_URL,
  CHATMESSAGE_TYPE_FILE,
  CHATMESSAGE_TYPE_TEXT,
  CHATMESSAGE_TYPE_IMAGE,
  CHATMESSAGE_TYPE_STICKER,
  CHATMESSAGE_TYPE_VIDEO,
  CHATMESSAGE_TYPE_RECORDING
}

export const CHATMESSAGE_TYPE_LIST = _.values(CHATMESSAGE_TYPE)
