// REDIS config key
export const REDIS_FOLLOWING_REWARD_OF_UNLOCK_CHAT =
  "FOLLOWING_REWARD_OF_UNLOCK_CHAT"
export const REDIS_SUBSCRIBEING_COIN = "SUBSCRIBEING_COIN"
export const REDIS_CHAT_COIN = "CHAT_COIN"
export const REDIS_SUBSCRIBING_REWARD_OF_UNLOCK_STORY =
  "SUBSCRIBING_REWARD_OF_UNLOCK_STORY"
export const REDIS_SUBSCRIBING_REWARD_OF_UNLOCK_CHAT =
  "SUBSCRIBING_REWARD_OF_UNLOCK_CHAT"
export const REDIS_PINNED_STORY_LENGTH = "PINNED_STORY_LENGTH"
