export const EMAIL_EVENT_REGISTER = "REGISTER"
export const EMAIL_EVENT_FORGOT_PASSWORD = "FORGOT_PASSWORD"
export const EMAIL_EVENT_COIN_NOT_ENOUGH = "COIN_NOT_ENOUGH"
export const EMAIL_EVENT_PROMOTION = "PROMOTION"
