export const FILE_PATH_BANNERS = "banners"
export const FILE_PATH_TOYS = "toys"
export const FILE_PATH_DEALERS_CONTRACT = "dealersContract"
export const FILE_PATH_STORIES = "stories"
export const FILE_PATH_CHATROOMS = "chatrooms"
export const FILE_PATH_USERS = "users"

export const FILE_TYPE_PNG = "image/png"
export const FILE_TYPE_JPG = "image/jpg"
export const FILE_TYPE_JPEG = "image/jpeg"
export const FILE_TYPE_MP4 = "video/mp4"
export const FILE_TYPE_MOV = "video/quicktime"
export const FILE_TYPE_MP3 = "audio/mp3"
export const FILE_TYPE_MPEG = "audio/mpeg"
export const FILE_TYPE_PDF = "application/pdf"
