export const ALL_RANK_ONEMONTH_ARTIST = "ALL_RANK_ONEMONTH_ARTIST"
export const UNLOCK_STORY_RANK_ONEMONTH_ARTIST =
  "UNLOCK_STORY_RANK_ONEMONTH_ARTIST"
export const UNLOCK_CHAT_RANK_ONEMONTH_ARTIST =
  "UNLOCK_CHAT_RANK_ONEMONTH_ARTIST"
export const SEND_TOY_RANK_ONEMONTH_ARTIST = "SEND_TOY_RANK_ONEMONTH_ARTIST"

export const ALL_RANK_ONEWEEK_ARTIST = "ALL_RANK_ONEWEEK_ARTIST"
export const UNLOCK_STORY_RANK_ONEWEEK_ARTIST =
  "UNLOCK_STORY_RANK_ONEWEEK_ARTIST"
export const UNLOCK_CHAT_RANK_ONEWEEK_ARTIST = "UNLOCK_CHAT_RANK_ONEWEEK_ARTIST"
export const SEND_TOY_RANK_ONEWEEK_ARTIST = "SEND_TOY_RANK_ONEWEEK_ARTIST"

export const ALL_RANK_ONEDAY_ARTIST = "ALL_RANK_ONEDAY_ARTIST"
export const UNLOCK_STORY_RANK_ONEDAY_ARTIST = "UNLOCK_STORY_RANK_ONEDAY_ARTIST"
export const UNLOCK_CHAT_RANK_ONEDAY_ARTIST = "UNLOCK_CHAT_RANK_ONEDAY_ARTIST"
export const SEND_TOY_RANK_ONEDAY_ARTIST = "SEND_TOY_RANK_ONEDAY_ARTIST"

export const ALL_RANK_ONEMONTH_CLIENT = "ALL_RANK_ONEMONTH_CLIENT"
export const UNLOCK_STORY_RANK_ONEMONTH_CLIENT =
  "UNLOCK_STORY_RANK_ONEMONTH_CLIENT"
export const UNLOCK_CHAT_RANK_ONEMONTH_CLIENT =
  "UNLOCK_CHAT_RANK_ONEMONTH_CLIENT"
export const SEND_TOY_RANK_ONEMONTH_CLIENT = "SEND_TOY_RANK_ONEMONTH_CLIENT"

export const ALL_RANK_ONEWEEK_CLIENT = "ALL_RANK_ONEWEEK_CLIENT"
export const UNLOCK_STORY_RANK_ONEWEEK_CLIENT =
  "UNLOCK_STORY_RANK_ONEWEEK_CLIENT"
export const UNLOCK_CHAT_RANK_ONEWEEK_CLIENT = "UNLOCK_CHAT_RANK_ONEWEEK_CLIENT"
export const SEND_TOY_RANK_ONEWEEK_CLIENT = "SEND_TOY_RANK_ONEWEEK_CLIENT"

export const ALL_RANK_ONEDAY_CLIENT = "ALL_RANK_ONEDAY_CLIENT"
export const UNLOCK_STORY_RANK_ONEDAY_CLIENT = "UNLOCK_STORY_RANK_ONEDAY_CLIENT"
export const UNLOCK_CHAT_RANK_ONEDAY_CLIENT = "UNLOCK_CHAT_RANK_ONEDAY_CLIENT"
export const SEND_TOY_RANK_ONEDAY_CLIENT = "SEND_TOY_RANK_ONEDAY_CLIENT"

export const ALL = "ALL"
export const UNLOCK_STORY = "UNLOCK_STORY"
export const UNLOCK_CHAT = "UNLOCK_CHAT"
export const SEND_TOY = "SEND_TOY"

export const ONEDAY = "ONEDAY"
export const ONEWEEK = "ONEWEEK"
export const ONEMONTH = "ONEMONTH"
