// 新訊息左上角提醒
export const CHATMESSAGE_NOTIFICATION = "CHATMESSAGE_NOTIFICATION"
// 聊天室訊息更新
export const CHATROOM_MESSAGE = "CHATROOM_MESSAGE"
// 聊天室訊息已讀更新
export const CHATROOM_MESSAGE_IS_READ_UPDATED =
  "CHATROOM_MESSAGE_IS_READ_UPDATED"
// 聊天室更新
export const CHATROOM_UPDATED = "CHATROOM_UPDATED"
// 追蹤主播貼文提醒
export const NEW_PUBLISHED_STORY_OF_FOLLOW_ARTIST =
  "NEW_PUBLISHED_STORY_OF_FOLLOW_ARTIST"
// 日誌新增通知
export const RECORD_NOTIFICATION = "RECORD_NOTIFICATION"
// 即時資訊變動通知
export const REALTIME_INFO = "REALTIME_INFO"
