import _ from "lodash"

// 性別
export const USER_GENDER_MALE = "MALE"
export const USER_GENDER_FEMALE = "FEMALE"

export const USER_GENDER = {
  USER_GENDER_MALE,
  USER_GENDER_FEMALE
}

export const USER_GENDER_LIST = _.values(USER_GENDER)

// 追蹤狀態
export const USER_FOLLOW_STATUS_FOLLOW = "FOLLOW"
export const USER_FOLLOW_STATUS_UNFOLLOW = "UNFOLLOW"

export const USER_FOLLOW_STATUS = {
  USER_FOLLOW_STATUS_FOLLOW,
  USER_FOLLOW_STATUS_UNFOLLOW
}

export const USER_FOLLOW_STATUS_LIST = _.values(USER_FOLLOW_STATUS)

// 訂閱狀態
export const USER_SUBSCRIBE_STATUS_SUBSCRIBE = "SUBSCRIBE"
export const USER_SUBSCRIBE_STATUS_UNSUBSCRIBE = "UNSUBSCRIBE"

export const USER_SUBSCRIBE_STATUS = {
  USER_SUBSCRIBE_STATUS_SUBSCRIBE,
  USER_SUBSCRIBE_STATUS_UNSUBSCRIBE
}

export const USER_SUBSCRIBE_STATUS_LIST = _.values(USER_SUBSCRIBE_STATUS)

// 封鎖狀態
export const USER_BLOCK_STATUS_BLOCK = "BLOCK"
export const USER_BLOCK_STATUS_UNBLOCK = "UNBLOCK"

export const USER_BLOCK_STATUS = {
  USER_BLOCK_STATUS_BLOCK,
  USER_BLOCK_STATUS_UNBLOCK
}

export const USER_BLOCK_STATUS_LIST = _.values(USER_BLOCK_STATUS)

export const USER_SOURCE_FACEBOOK = "FACEBOOK"
export const USER_SOURCE_GOOGLE = "GOOGLE"
export const USER_SOURCE_CUSTOM = "CUSTOM"
export const USER_SOURCE_BACK = "BACK"

export const USER_SOURCE = {
  USER_SOURCE_FACEBOOK,
  USER_SOURCE_GOOGLE,
  USER_SOURCE_CUSTOM,
  USER_SOURCE_BACK
}

export const USER_SOURCE_LIST = _.values(USER_SOURCE)

export const USER_SCOPE_FRONT = "FRONT_ONLY"
export const USER_SCOPE_BACK = "BACK_ONLY"

export const USER_SCOPE = {
  USER_SCOPE_FRONT,
  USER_SCOPE_BACK
}

export const USER_SCOPE_LIST = _.values(USER_SCOPE)

export const USER_INVOICE_PERSONAL = "PERSONAL"
export const USER_INVOICE_LOVE = "LOVE"

export const USER_INVOICE = {
  USER_INVOICE_PERSONAL,
  USER_INVOICE_LOVE
}

export const USER_INVOICE_LIST = _.values(USER_INVOICE)
