import _ from "lodash"

export const VOUCHER_TYPE_UNLOCK_CHAT = "UNLOCK_CHAT"
export const VOUCHER_TYPE_UNLOCK_STORY = "UNLOCK_STORY"

export const VOUCHER_TYPE = {
  VOUCHER_TYPE_UNLOCK_CHAT,
  VOUCHER_TYPE_UNLOCK_STORY
}

export const VOUCHER_TYPE_LIST = _.values(VOUCHER_TYPE)

export const VOUCHER_STATUS_ACTIVED = "ACTIVED"
export const VOUCHER_STATUS_USED = "USED"
export const VOUCHER_STATUS_EXPIRED = "EXPIRED"

export const VOUCHER_STATUS = {
  VOUCHER_STATUS_ACTIVED,
  VOUCHER_STATUS_USED,
  VOUCHER_STATUS_EXPIRED
}

export const VOUCHER_STATUS_LIST = _.values(VOUCHER_STATUS)

export const VOUCHER_SOURCE_FOLLOWING = "FOLLOWING"
export const VOUCHER_SOURCE_SUBSCIBING = "SUBSCIBING"
export const VOUCHER_SOURCE_PROMOTION = "PROMOTION"
export const VOUCHER_SOURCE_GIFT = "GIFT"

export const VOUCHER_SOURCE = {
  VOUCHER_SOURCE_FOLLOWING,
  VOUCHER_SOURCE_SUBSCIBING,
  VOUCHER_SOURCE_PROMOTION,
  VOUCHER_SOURCE_GIFT
}
export const VOUCHER_SOURCE_LIST = _.values(VOUCHER_SOURCE)
