import dataProvider from "./dataProvider"
import {
  banner,
  chatmessage,
  chatroom,
  coin,
  consumeHistory,
  dealer,
  invoice,
  feature,
  log,
  loginHistory,
  order,
  promotion,
  record,
  reward,
  roleFeature,
  share,
  story,
  storyBlock,
  storyNotification,
  storyTag,
  subscribe,
  toy,
  toyType,
  user,
  viewLog,
  voucher
} from "../models"

export default {
  banner: dataProvider(banner),
  chatmessage: dataProvider(chatmessage),
  chatroom: dataProvider(chatroom),
  coin: dataProvider(coin),
  consumeHistory: dataProvider(consumeHistory),
  dealer: dataProvider(dealer),
  feature: dataProvider(feature),
  invoice: dataProvider(invoice),
  log: dataProvider(log),
  loginHistory: dataProvider(loginHistory),
  order: dataProvider(order),
  promotion: dataProvider(promotion),
  record: dataProvider(record),
  reward: dataProvider(reward),
  roleFeature: dataProvider(roleFeature),
  share: dataProvider(share),
  story: dataProvider(story),
  storyBlock: dataProvider(storyBlock),
  storyNotification: dataProvider(storyNotification),
  storyTag: dataProvider(storyTag),
  toy: dataProvider(toy),
  toyType: dataProvider(toyType),
  subscribe: dataProvider(subscribe),
  user: dataProvider(user),
  viewLog: dataProvider(viewLog),
  voucher: dataProvider(voucher)
}
