import { ADMIN, MANAGER, DEALER, CLIENT, ARTIST } from "./constants"

const permissionSet = {
  archives: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  archive: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  frontBanners: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  banners: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  banner: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  createBanner: [ADMIN, MANAGER],
  updateBanner: [ADMIN, MANAGER],
  deleteBanner: [ADMIN, MANAGER],
  chatroomChatMessages: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  createChatmessage: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  createChatmessages: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  artistChatrooms: [ADMIN, MANAGER, DEALER],
  artistChatroom: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  chatrooms: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  chatroom: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  frontCoins: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  coins: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  coin: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  createCoin: [ADMIN, MANAGER],
  updateCoin: [ADMIN, MANAGER],
  configuration: [ADMIN, MANAGER],
  updateConfiguration: [ADMIN, MANAGER],
  consumeHistories: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  consumeHistory: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  createConsumeHistory: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  updateConsumeHistory: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  dealers: [ADMIN, MANAGER, DEALER],
  dealer: [ADMIN, MANAGER, DEALER],
  createDealer: [ADMIN, MANAGER],
  updateDealer: [ADMIN, MANAGER, DEALER],
  features: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  feature: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  createFeature: [ADMIN, MANAGER],
  updateFeature: [ADMIN, MANAGER],
  deleteFeature: [ADMIN, MANAGER],
  loginHistories: [ADMIN, MANAGER],
  loginHistory: [ADMIN, MANAGER],
  orders: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  order: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  createOrder: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  updateOrder: [ADMIN, MANAGER],
  deleteOrder: [ADMIN, MANAGER],
  frontPromotions: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  promotions: [ADMIN, MANAGER],
  promotion: [ADMIN, MANAGER],
  createPromotion: [ADMIN, MANAGER],
  updatePromotion: [ADMIN, MANAGER],
  deletePromotion: [ADMIN, MANAGER],
  rankings: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  userRecords: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  records: [ADMIN, MANAGER, DEALER],
  record: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  dealerReports: [ADMIN, MANAGER, DEALER],
  rewards: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  reward: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  createReward: [ADMIN, MANAGER],
  updateReward: [ADMIN, MANAGER],
  deleteReward: [ADMIN, MANAGER],
  roleFeatures: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  roleFeature: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  createRoleFeature: [ADMIN, MANAGER],
  updateRoleFeature: [ADMIN, MANAGER],
  deleteRoleFeature: [ADMIN, MANAGER],
  freeStories: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  pinnedStories: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  searchStories: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  artistStories: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  storyTagStories: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  storyBlockStories: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  frontStories: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  ownStories: [ARTIST],
  stories: [ADMIN, MANAGER, ARTIST, DEALER],
  story: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  createStory: [ADMIN, MANAGER, ARTIST],
  updateStory: [ADMIN, MANAGER],
  deleteStory: [ADMIN, MANAGER],
  frontStoryBlocks: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  storyBlocks: [ADMIN, MANAGER],
  storyBlock: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  createStoryBlock: [ADMIN, MANAGER],
  updateStoryBlock: [ADMIN, MANAGER],
  updateStoryBlocks: [ADMIN, MANAGER],
  deleteStoryBlock: [ADMIN, MANAGER],
  storyNotifications: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  readStoryNotification: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  searchStoryTags: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  storyTags: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  storyTag: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  createStoryTag: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  subscribes: [ADMIN, MANAGER],
  subscribe: [ADMIN, MANAGER],
  createSubscribe: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  updateSubscribe: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  deleteSubscribe: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  toys: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  toy: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  createToy: [ADMIN, MANAGER],
  updateToy: [ADMIN, MANAGER],
  deleteToy: [ADMIN, MANAGER],
  toyTypes: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  toyType: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  createToyType: [ADMIN, MANAGER],
  updateToyType: [ADMIN, MANAGER],
  deleteToyType: [ADMIN, MANAGER],
  searchDateableArtists: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  searchArtists: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  searchDealerUsers: [ADMIN, MANAGER, DEALER],
  searchUsers: [ADMIN, MANAGER],
  artists: [ADMIN, MANAGER, DEALER],
  users: [ADMIN, MANAGER, DEALER],
  user: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  me: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  createUser: [ADMIN, MANAGER, DEALER],
  updateUser: [ADMIN, MANAGER, DEALER],
  updateUserInfo: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  updateUserUid: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  followingUser: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  subscribingUser: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  blockingUser: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  artistVouchers: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  vouchers: [ADMIN, MANAGER],
  voucher: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  createVoucher: [ADMIN, MANAGER],
  updateVoucher: [ADMIN, MANAGER],
  deleteVoucher: [ADMIN, MANAGER],
  viewLogs: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  viewLog: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST],
  createViewLog: [ADMIN, MANAGER, DEALER, CLIENT, ARTIST]
}

export default permissionSet
